[build]
publish = "public"
command = "hugo --baseURL $URL"

[context.deploy-preview]
publish = "public"
command = "hugo"

[context.production.environment]
HUGO_VERSION = "0.49.2"

[context.deploy-preview.environment]
HUGO_VERSION = "0.49.2"
